### ISSUE TITLE
Update to httpclient5 v5.2.2 fails with an invalid proxy exception

### ISSUE THREAD

**Issue by javiertuya** [giis-uniovi/tdrules#94]
If this new version of httpclient5 is used, calls made from the client fail with this exception:

```
java.lang.IllegalArgumentException: Invalid Proxy
at java.base/java.net.Socket.<init>(Unknown Source)
at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.createSocket(SSLConnectionSocketFactory.java:208)
at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:447)
at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:162)
at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:172)
at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:142)
at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:106)
at giis.tdrules.openapi.invoker.ApiClient.invokeAPI(ApiClient.java:953)
at giis.tdrules.openapi.api.TdRulesApi.rulesPost(TdRulesApi.java:400)
at giis.tdrules.openapi.api.TdRulesApi.rulesPost(TdRulesApi.java:351)
at giis.tdrules.client.TdRulesApi.getRules(TdRulesApi.java:55)
```

Maybe it depends on how the openapi generator creates the api client (default version of httpclient5 is still 5.1.3. Worked until now with 5.2.1

Workaround: delete the update branch to close PR that udpates to this version.

**Comment by javiertuya** [comment]
Released new version of httpclient that fixes the issue
